### ISSUE TITLE
Croatia

### ISSUE THREAD

**Issue by sthenc** [marado/TTIPTuesday#17]
Pošalji
# CETA i #TTIP = mnogo opasnosti, malo prednosti, i bez mogućnosti povratka. Ne isplati se. #SayNo

Europski zastupnik
Svaki utorak šaljemo tweetove o #TTIP europskim zastupnicima. Ova web stranica nam treba olakšati taj posao.
Tekst za poslati:

**Comment by marado** [comment]
Thanks for your translations submission!
Please let me know if something's not quite well (I'm afraid I know nothing of Croatian).

**Comment by sthenc** [comment]
Hi, I am happy to help.

There seems to be a problem, the page http://marado.github.io/TTIPTuesday/croatia.html currently shows the wrong MEP's. I think this should fix it https://github.com/marado/TTIPTuesday/pull/18

**Comment by marado** [comment]
Yikes, this is what happens when you do something in a rush... Thanks for
the patch!
